<a href="https://colab.research.google.com/github/Fahim-Bin-Rafiq/Data-Analytic/blob/main/NumPy_Essentials_Practice_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

In [1]:
import numpy as np

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In Python, the major difference between a vector and a matrix lies in how they are represented and manipulated using libraries such as NumPy:

Vector:

In Python, a vector can be represented as a one-dimensional NumPy array.
A vector can be created using np.array() function from NumPy, and it can contain a sequence of numerical values along a single dimension.
Vectors can be operated on element-wise using mathematical operations or vectorized functions in NumPy.
Example:

import numpy as np

vector = np.array([1, 2, 3, 4, 5])

Matrix:

In Python, a matrix can be represented as a two-dimensional NumPy array.
A matrix can be created using np.array() function from NumPy, and it can contain numerical values arranged in rows and columns.
Matrices can be operated on using various matrix operations provided by NumPy, such as matrix multiplication, addition, subtraction, and more.
Example:

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [ ]:
# Please consult the lectures

**2. How to import `NumPy` library?**

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [ ]:
list_1 = [1,2,3,4,5]

In [ ]:
# To avoid overwriting the output, please code here

list_1 = [1,2,3,4,5]
arry_list=np.array(list_1)
arry_list,type(arry_list)


(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [ ]:
list_1 = [1,2,3,4,5]
arry_list=np.array(list_1)
arry_list,type(arry_list)


(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [ ]:
# To avoid overwriting the output, please code here
num = np.arange(6)
num

array([0, 1, 2, 3, 4, 5])

In [ ]:
num = np.arange(6)
num

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [ ]:
# To avoid overwriting the output, please code here
zeros_array = np.zeros(5)

zeros_array

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_array = np.zeros(5)

zeros_array

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [ ]:
# To avoid overwriting the output, please code here

zeros_array = np.zeros((3,4))

zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zeros_array = np.zeros((3,4))

zeros_array

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [ ]:
# To avoid overwriting the output, please code here

ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [ ]:
ones_array = np.ones(5)
print(ones_array)

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [ ]:
# To avoid overwriting the output, please code here

tens_array = np.full(5, 10 ,dtype=float)
tens_array

array([10., 10., 10., 10., 10.])

In [ ]:

tens_array = np.full(5, 10 ,dtype=float)
tens_array

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [ ]:
# To avoid overwriting the output, please code here

even_num=np.arange(52,100,2)
even_num

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [ ]:
even_num=np.arange(52,100,2)
even_num

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [ ]:
# To avoid overwriting the output, please code here
import numpy as np

x=np.linspace(0, 1, 10, retstep=True)
x



(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

In [ ]:
x=np.linspace(0, 1, 10, retstep=True)
x

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [ ]:
# To avoid overwriting the output, please code here
vector=np.arange(25)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Generating vector array
vector=np.arange(25)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# To avoid overwriting the output, please code here
vector.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# reshape to convert into 2-d
vector.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# To avoid overwriting the output, please code here

vector=np.arange(25)
vector.shape=(5,5)
vector


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Using shape

vector=np.arange(25)
vector.shape=(5,5)
vector

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [ ]:

linear_points = np.linspace(0.1, 2.5, 25)

matrix = linear_points.reshape(5, 5)

matrix


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

# To avoid overwriting the output, please code here




In [ ]:
linear_points = np.linspace(0.1, 2.5, 25)

matrix = linear_points.reshape(5, 5)

matrix

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [ ]:
# To avoid overwriting the output, please code here

linear_points = np.linspace(0, 24, 25, dtype=int)


matrix = linear_points.reshape(5, 5)
print(matrix)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
linear_points = np.linspace(0, 24, 25, dtype=int)


matrix = linear_points.reshape(5, 5)
print(matrix)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# Please consult the lectures.
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

The numpy.arange() returns evenly spaced values within a given interval. Values are generated within the half-open interval [start, stop) (in other words, the interval includes the start but excludes the stop). For integer arguments, the function is equivalent to the Python built-in range function but returns a ndarray rather than a list.

The numpy.linspace() returns evenly spaced numbers over a specified interval. The output is num; evenly spaced samples, calculated over the interval [start, stop]. The endpoint of the interval can optionally be excluded.

**15. How to generate a single random integer number using NumPy built-in function?**

In [ ]:
# To avoid overwriting the output, please code here
random_number = np.random.randint(100)

random_number


74

In [ ]:
#  ANS:To generate a single random integer number we use NumPys random.randint()built-in function
random_number = np.random.randint(100)

random_number

51

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [ ]:
# To avoid overwriting the output, please code here
matrix = np.random.rand(7, 5)

print(matrix)

[[0.49095681 0.89752191 0.52862715 0.30432342 0.83442122]
 [0.00776339 0.63747167 0.34931303 0.57147694 0.38878827]
 [0.99306315 0.4983348  0.97656921 0.94801018 0.85945722]
 [0.41177669 0.31083044 0.39523904 0.33269011 0.10599952]
 [0.33146284 0.76636579 0.20845911 0.37280733 0.90459368]
 [0.14689069 0.6097612  0.65430616 0.74917636 0.20767125]
 [0.40585082 0.60949422 0.52606789 0.34636268 0.93542332]]


In [ ]:
matrix = np.random.rand(7, 5)

print(matrix)

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [ ]:
# To avoid overwriting the output, please code here
matrix = np.eye(5) * 5

matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [ ]:
matrix = np.eye(5) * 5

matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck